INSERT INTO `languages` (`id`, `value`) VALUES ('ab', 'Abkhazian');
INSERT INTO `languages` (`id`, `value`) VALUES ('ace', 'Achinese');
INSERT INTO `languages` (`id`, `value`) VALUES ('ada', 'Adangme');
INSERT INTO `languages` (`id`, `value`) VALUES ('ady', 'Adyghe');
INSERT INTO `languages` (`id`, `value`) VALUES ('aa', 'Afar');
INSERT INTO `languages` (`id`, `value`) VALUES ('afh', 'Afrihili');
INSERT INTO `languages` (`id`, `value`) VALUES ('af', 'Afrikaans');
INSERT INTO `languages` (`id`, `value`) VALUES ('agq', 'Aghem');
INSERT INTO `languages` (`id`, `value`) VALUES ('ain', 'Ainu');
INSERT INTO `languages` (`id`, `value`) VALUES ('ak', 'Akan');
INSERT INTO `languages` (`id`, `value`) VALUES ('akk', 'Akkadian');
INSERT INTO `languages` (`id`, `value`) VALUES ('bss', 'Akoose');
INSERT INTO `languages` (`id`, `value`) VALUES ('akz', 'Alabama');
INSERT INTO `languages` (`id`, `value`) VALUES ('sq', 'Albanian');
INSERT INTO `languages` (`id`, `value`) VALUES ('ale', 'Aleut');
INSERT INTO `languages` (`id`, `value`) VALUES ('arq', 'Algerian Arabic');
INSERT INTO `languages` (`id`, `value`) VALUES ('en_US', 'American English');
INSERT INTO `languages` (`id`, `value`) VALUES ('ase', 'American Sign Language');
INSERT INTO `languages` (`id`, `value`) VALUES ('am', 'Amharic');
INSERT INTO `languages` (`id`, `value`) VALUES ('egy', 'Ancient Egyptian');
INSERT INTO `languages` (`id`, `value`) VALUES ('grc', 'Ancient Greek');
INSERT INTO `languages` (`id`, `value`) VALUES ('anp', 'Angika');
INSERT INTO `languages` (`id`, `value`) VALUES ('njo', 'Ao Naga');
INSERT INTO `languages` (`id`, `value`) VALUES ('ar', 'Arabic');
INSERT INTO `languages` (`id`, `value`) VALUES ('an', 'Aragonese');
INSERT INTO `languages` (`id`, `value`) VALUES ('arc', 'Aramaic');
INSERT INTO `languages` (`id`, `value`) VALUES ('aro', 'Araona');
INSERT INTO `languages` (`id`, `value`) VALUES ('arp', 'Arapaho');
INSERT INTO `languages` (`id`, `value`) VALUES ('arw', 'Arawak');
INSERT INTO `languages` (`id`, `value`) VALUES ('hy', 'Armenian');
INSERT INTO `languages` (`id`, `value`) VALUES ('rup', 'Aromanian');
INSERT INTO `languages` (`id`, `value`) VALUES ('frp', 'Arpitan');
INSERT INTO `languages` (`id`, `value`) VALUES ('as', 'Assamese');
INSERT INTO `languages` (`id`, `value`) VALUES ('ast', 'Asturian');
INSERT INTO `languages` (`id`, `value`) VALUES ('asa', 'Asu');
INSERT INTO `languages` (`id`, `value`) VALUES ('cch', 'Atsam');
INSERT INTO `languages` (`id`, `value`) VALUES ('en_AU', 'Australian English');
INSERT INTO `languages` (`id`, `value`) VALUES ('de_AT', 'Austrian German');
INSERT INTO `languages` (`id`, `value`) VALUES ('av', 'Avaric');
INSERT INTO `languages` (`id`, `value`) VALUES ('ae', 'Avestan');
INSERT INTO `languages` (`id`, `value`) VALUES ('awa', 'Awadhi');
INSERT INTO `languages` (`id`, `value`) VALUES ('ay', 'Aymara');
INSERT INTO `languages` (`id`, `value`) VALUES ('az', 'Azerbaijani');
INSERT INTO `languages` (`id`, `value`) VALUES ('bfq', 'Badaga');
INSERT INTO `languages` (`id`, `value`) VALUES ('ksf', 'Bafia');
INSERT INTO `languages` (`id`, `value`) VALUES ('bfd', 'Bafut');
INSERT INTO `languages` (`id`, `value`) VALUES ('bqi', 'Bakhtiari');
INSERT INTO `languages` (`id`, `value`) VALUES ('ban', 'Balinese');
INSERT INTO `languages` (`id`, `value`) VALUES ('bal', 'Baluchi');
INSERT INTO `languages` (`id`, `value`) VALUES ('bm', 'Bambara');
INSERT INTO `languages` (`id`, `value`) VALUES ('bax', 'Bamun');
INSERT INTO `languages` (`id`, `value`) VALUES ('bjn', 'Banjar');
INSERT INTO `languages` (`id`, `value`) VALUES ('bas', 'Basaa');
INSERT INTO `languages` (`id`, `value`) VALUES ('ba', 'Bashkir');
INSERT INTO `languages` (`id`, `value`) VALUES ('eu', 'Basque');
INSERT INTO `languages` (`id`, `value`) VALUES ('bbc', 'Batak Toba');
INSERT INTO `languages` (`id`, `value`) VALUES ('bar', 'Bavarian');
INSERT INTO `languages` (`id`, `value`) VALUES ('bej', 'Beja');
INSERT INTO `languages` (`id`, `value`) VALUES ('be', 'Belarusian');
INSERT INTO `languages` (`id`, `value`) VALUES ('bem', 'Bemba');
INSERT INTO `languages` (`id`, `value`) VALUES ('bez', 'Bena');
INSERT INTO `languages` (`id`, `value`) VALUES ('bn', 'Bengali');
INSERT INTO `languages` (`id`, `value`) VALUES ('bew', 'Betawi');
INSERT INTO `languages` (`id`, `value`) VALUES ('bho', 'Bhojpuri');
INSERT INTO `languages` (`id`, `value`) VALUES ('bik', 'Bikol');
INSERT INTO `languages` (`id`, `value`) VALUES ('bin', 'Bini');
INSERT INTO `languages` (`id`, `value`) VALUES ('bpy', 'Bishnupriya');
INSERT INTO `languages` (`id`, `value`) VALUES ('bi', 'Bislama');
INSERT INTO `languages` (`id`, `value`) VALUES ('byn', 'Blin');
INSERT INTO `languages` (`id`, `value`) VALUES ('zbl', 'Blissymbols');
INSERT INTO `languages` (`id`, `value`) VALUES ('brx', 'Bodo');
INSERT INTO `languages` (`id`, `value`) VALUES ('bs', 'Bosnian');
INSERT INTO `languages` (`id`, `value`) VALUES ('brh', 'Brahui');
INSERT INTO `languages` (`id`, `value`) VALUES ('bra', 'Braj');
INSERT INTO `languages` (`id`, `value`) VALUES ('pt_BR', 'Brazilian Portuguese');
INSERT INTO `languages` (`id`, `value`) VALUES ('br', 'Breton');
INSERT INTO `languages` (`id`, `value`) VALUES ('en_GB', 'British English');
INSERT INTO `languages` (`id`, `value`) VALUES ('bug', 'Buginese');
INSERT INTO `languages` (`id`, `value`) VALUES ('bg', 'Bulgarian');
INSERT INTO `languages` (`id`, `value`) VALUES ('bum', 'Bulu');
INSERT INTO `languages` (`id`, `value`) VALUES ('bua', 'Buriat');
INSERT INTO `languages` (`id`, `value`) VALUES ('my', 'Burmese');
INSERT INTO `languages` (`id`, `value`) VALUES ('cad', 'Caddo');
INSERT INTO `languages` (`id`, `value`) VALUES ('frc', 'Cajun French');
INSERT INTO `languages` (`id`, `value`) VALUES ('en_CA', 'Canadian English');
INSERT INTO `languages` (`id`, `value`) VALUES ('fr_CA', 'Canadian French');
INSERT INTO `languages` (`id`, `value`) VALUES ('yue', 'Cantonese');
INSERT INTO `languages` (`id`, `value`) VALUES ('cps', 'Capiznon');
INSERT INTO `languages` (`id`, `value`) VALUES ('car', 'Carib');
INSERT INTO `languages` (`id`, `value`) VALUES ('ca', 'Catalan');
INSERT INTO `languages` (`id`, `value`) VALUES ('cay', 'Cayuga');
INSERT INTO `languages` (`id`, `value`) VALUES ('ceb', 'Cebuano');
INSERT INTO `languages` (`id`, `value`) VALUES ('tzm', 'Central Atlas Tamazight');
INSERT INTO `languages` (`id`, `value`) VALUES ('dtp', 'Central Dusun');
INSERT INTO `languages` (`id`, `value`) VALUES ('esu', 'Central Yupik');
INSERT INTO `languages` (`id`, `value`) VALUES ('shu', 'Chadian Arabic');
INSERT INTO `languages` (`id`, `value`) VALUES ('chg', 'Chagatai');
INSERT INTO `languages` (`id`, `value`) VALUES ('ch', 'Chamorro');
INSERT INTO `languages` (`id`, `value`) VALUES ('ce', 'Chechen');
INSERT INTO `languages` (`id`, `value`) VALUES ('chr', 'Cherokee');
INSERT INTO `languages` (`id`, `value`) VALUES ('chy', 'Cheyenne');
INSERT INTO `languages` (`id`, `value`) VALUES ('chb', 'Chibcha');
INSERT INTO `languages` (`id`, `value`) VALUES ('cgg', 'Chiga');
INSERT INTO `languages` (`id`, `value`) VALUES ('qug', 'Chimborazo Highland Quichua');
INSERT INTO `languages` (`id`, `value`) VALUES ('zh', 'Chinese');
INSERT INTO `languages` (`id`, `value`) VALUES ('chn', 'Chinook Jargon');
INSERT INTO `languages` (`id`, `value`) VALUES ('chp', 'Chipewyan');
INSERT INTO `languages` (`id`, `value`) VALUES ('cho', 'Choctaw');
INSERT INTO `languages` (`id`, `value`) VALUES ('cu', 'Church Slavic');
INSERT INTO `languages` (`id`, `value`) VALUES ('chk', 'Chuukese');
INSERT INTO `languages` (`id`, `value`) VALUES ('cv', 'Chuvash');
INSERT INTO `languages` (`id`, `value`) VALUES ('nwc', 'Classical Newari');
INSERT INTO `languages` (`id`, `value`) VALUES ('syc', 'Classical Syriac');
INSERT INTO `languages` (`id`, `value`) VALUES ('ksh', 'Colognian');
INSERT INTO `languages` (`id`, `value`) VALUES ('swb', 'Comorian');
INSERT INTO `languages` (`id`, `value`) VALUES ('swc', 'Congo Swahili');
INSERT INTO `languages` (`id`, `value`) VALUES ('cop', 'Coptic');
INSERT INTO `languages` (`id`, `value`) VALUES ('kw', 'Cornish');
INSERT INTO `languages` (`id`, `value`) VALUES ('co', 'Corsican');
INSERT INTO `languages` (`id`, `value`) VALUES ('cr', 'Cree');
INSERT INTO `languages` (`id`, `value`) VALUES ('mus', 'Creek');
INSERT INTO `languages` (`id`, `value`) VALUES ('crh', 'Crimean Turkish');
INSERT INTO `languages` (`id`, `value`) VALUES ('hr', 'Croatian');
INSERT INTO `languages` (`id`, `value`) VALUES ('cs', 'Czech');
INSERT INTO `languages` (`id`, `value`) VALUES ('dak', 'Dakota');
INSERT INTO `languages` (`id`, `value`) VALUES ('da', 'Danish');
INSERT INTO `languages` (`id`, `value`) VALUES ('dar', 'Dargwa');
INSERT INTO `languages` (`id`, `value`) VALUES ('dzg', 'Dazaga');
INSERT INTO `languages` (`id`, `value`) VALUES ('del', 'Delaware');
INSERT INTO `languages` (`id`, `value`) VALUES ('din', 'Dinka');
INSERT INTO `languages` (`id`, `value`) VALUES ('dv', 'Divehi');
INSERT INTO `languages` (`id`, `value`) VALUES ('doi', 'Dogri');
INSERT INTO `languages` (`id`, `value`) VALUES ('dgr', 'Dogrib');
INSERT INTO `languages` (`id`, `value`) VALUES ('dua', 'Duala');
INSERT INTO `languages` (`id`, `value`) VALUES ('nl', 'Dutch');
INSERT INTO `languages` (`id`, `value`) VALUES ('dyu', 'Dyula');
INSERT INTO `languages` (`id`, `value`) VALUES ('dz', 'Dzongkha');
INSERT INTO `languages` (`id`, `value`) VALUES ('frs', 'Eastern Frisian');
INSERT INTO `languages` (`id`, `value`) VALUES ('efi', 'Efik');
INSERT INTO `languages` (`id`, `value`) VALUES ('arz', 'Egyptian Arabic');
INSERT INTO `languages` (`id`, `value`) VALUES ('eka', 'Ekajuk');
INSERT INTO `languages` (`id`, `value`) VALUES ('elx', 'Elamite');
INSERT INTO `languages` (`id`, `value`) VALUES ('ebu', 'Embu');
INSERT INTO `languages` (`id`, `value`) VALUES ('egl', 'Emilian');
INSERT INTO `languages` (`id`, `value`) VALUES ('en', 'English');
INSERT INTO `languages` (`id`, `value`) VALUES ('myv', 'Erzya');
INSERT INTO `languages` (`id`, `value`) VALUES ('eo', 'Esperanto');
INSERT INTO `languages` (`id`, `value`) VALUES ('et', 'Estonian');
INSERT INTO `languages` (`id`, `value`) VALUES ('pt_PT', 'European Portuguese');
INSERT INTO `languages` (`id`, `value`) VALUES ('es_ES', 'European Spanish');
INSERT INTO `languages` (`id`, `value`) VALUES ('ee', 'Ewe');
INSERT INTO `languages` (`id`, `value`) VALUES ('ewo', 'Ewondo');
INSERT INTO `languages` (`id`, `value`) VALUES ('ext', 'Extremaduran');
INSERT INTO `languages` (`id`, `value`) VALUES ('fan', 'Fang');
INSERT INTO `languages` (`id`, `value`) VALUES ('fat', 'Fanti');
INSERT INTO `languages` (`id`, `value`) VALUES ('fo', 'Faroese');
INSERT INTO `languages` (`id`, `value`) VALUES ('hif', 'Fiji Hindi');
INSERT INTO `languages` (`id`, `value`) VALUES ('fj', 'Fijian');
INSERT INTO `languages` (`id`, `value`) VALUES ('fil', 'Filipino');
INSERT INTO `languages` (`id`, `value`) VALUES ('fi', 'Finnish');
INSERT INTO `languages` (`id`, `value`) VALUES ('nl_BE', 'Flemish');
INSERT INTO `languages` (`id`, `value`) VALUES ('fon', 'Fon');
INSERT INTO `languages` (`id`, `value`) VALUES ('gur', 'Frafra');
INSERT INTO `languages` (`id`, `value`) VALUES ('fr', 'French');
INSERT INTO `languages` (`id`, `value`) VALUES ('fur', 'Friulian');
INSERT INTO `languages` (`id`, `value`) VALUES ('ff', 'Fulah');
INSERT INTO `languages` (`id`, `value`) VALUES ('gaa', 'Ga');
INSERT INTO `languages` (`id`, `value`) VALUES ('gag', 'Gagauz');
INSERT INTO `languages` (`id`, `value`) VALUES ('gl', 'Galician');
INSERT INTO `languages` (`id`, `value`) VALUES ('gan', 'Gan Chinese');
INSERT INTO `languages` (`id`, `value`) VALUES ('lg', 'Ganda');
INSERT INTO `languages` (`id`, `value`) VALUES ('gay', 'Gayo');
INSERT INTO `languages` (`id`, `value`) VALUES ('gba', 'Gbaya');
INSERT INTO `languages` (`id`, `value`) VALUES ('gez', 'Geez');
INSERT INTO `languages` (`id`, `value`) VALUES ('ka', 'Georgian');
INSERT INTO `languages` (`id`, `value`) VALUES ('de', 'German');
INSERT INTO `languages` (`id`, `value`) VALUES ('aln', 'Gheg Albanian');
INSERT INTO `languages` (`id`, `value`) VALUES ('bbj', 'Ghomala');
INSERT INTO `languages` (`id`, `value`) VALUES ('glk', 'Gilaki');
INSERT INTO `languages` (`id`, `value`) VALUES ('gil', 'Gilbertese');
INSERT INTO `languages` (`id`, `value`) VALUES ('gom', 'Goan Konkani');
INSERT INTO `languages` (`id`, `value`) VALUES ('gon', 'Gondi');
INSERT INTO `languages` (`id`, `value`) VALUES ('gor', 'Gorontalo');
